policies:
  shell:
    mode: strict
    allow: []
    deny:
      - "*"

name: artist-ui-refactor
description: >
  Safe, staged UI/UX refactor workflow for Next.js projects.
  Prevents hallucinations and large unintended rewrites.

steps:
  - id: audit
    name: Architecture & Performance Audit
    model: gemini-2.5-pro-preview
    input:
      include:
        - app/**
        - components/**
        - context/**
        - styles/**
    prompt: |
      You are analyzing an existing Next.js App Router project.

      Rules:
      - Do NOT change any code.
      - Only read and report.
      - Only talk about files that exist.
      - No assumptions.

      Tasks:
      1. Map the navigation flow (NavContext, view modes, modals).
      2. Identify why loading feels slow:
         - context re-renders
         - image loading
         - animations
         - carousels
      3. List which components rerender when:
         - filters change
         - a modal opens
         - navigation switches

      Output:
      - A short architecture summary
      - A bullet list of performance bottlenecks
      - A file list ranked by impact

  - id: nav-refactor
    name: Navigation & Filter System Refactor
    model: gemini-2.5-pro-preview
    depends_on: audit
    input:
      include:
        - app/**
        - components/nav/**
        - context/NavContext.*
        - context/WorksContext.*
        - context/ExhibitionsContext.*
    prompt: |
      Refactor ONLY the menu/nav and filter system.

      Scope:
      - Nav components
      - NavContext
      - Filter UI in the nav

      Rules:
      - Do not touch modals, carousels, or pages.
      - Replace custom buttons/selects with shadcn components.
      - Add:
        - Apply Filters button
        - Clear Filters button
        - Loader that says "Applying filters…"
      - On mobile:
        - Menu closes when a nav link is clicked
        - Menu closes when filters are applied/cleared
      - Add smooth open/close animations when switching views.

      Output:
      - List of changed files
      - Full updated components or diffs

  - id: modal-nav
    name: Modal Keyboard & Swipe Navigation
    model: gemini-2.5-pro-preview
    depends_on: nav-refactor
    input:
      include:
        - components/works/**
        - components/exhibitions/**
        - context/WorksContext.*
        - context/ExhibitionsContext.*
    prompt: |
      Refactor ONLY modal navigation behavior.

      Scope:
      - WorkModal
      - ExhibitionModal
      - Carousel navigation logic

      Rules:
      - Do not change layout styles unless specified.
      - Add keyboard navigation (desktop):
        ArrowLeft / ArrowRight → prev/next
      - Use:
        filteredWorks
        filteredExhibitions
      - Add swipe navigation on mobile.

      Exhibition modal:
      - center text/images on mobile
      - left align on desktop

      Output:
      - Updated modal components
      - Any new hooks or utilities

  - id: typography
    name: Typography, Dividers & Info View
    model: gemini-2.5-pro-preview
    depends_on: modal-nav
    input:
      include:
        - app/**
        - components/**
        - styles/**
    prompt: |
      Refactor ONLY typography and dividers.

      Scope:
      - Global styles
      - HDivider / VDivider
      - Information view

      Rules:
      - Create global CSS classes:
        .h1 .h2 .h3 .p .small
      - Replace all inline text styling with those classes.
      - Make Information view resemble lined paper.
      - Use dividers only for:
        lists
        structured blocks
      - If a divider contains a Link, make it blue.
      - Add "Back to Top" buttons to:
        MainContent
        ExhibitionModal

      Output:
      - Global styles file
      - Updated components

  - id: polish-performance-scroll
    name: Scroll, Sharing, Desktop Nav Defaults & Performance Hardening
    model: gemini-2.5-pro-preview
    depends_on: typography
    input:
      include:
        - app/**
        - components/**
        - context/**
        - lib/**
        - styles/**
    prompt: |
      Final hardening pass. Apply the following changes exactly as described.

      ------------------------------------------------
      1. Scrolling System
      ------------------------------------------------
      - Ensure scrolling works in every view and modal.
      - Hide native scrollbars in all browsers.
      - Use Lenis for all scrolling.
      - Add "Back to Top" buttons to:
        - MainContent
        - ExhibitionModal


      ------------------------------------------------
      2. Work Modal Share Button
      ------------------------------------------------
      - Add a discreet share button in WorkModal:
        - Top-right
        - Aligned to the same baseline as the work title/info.
      - On click:
        - Copy the absolute URL of the work slug page.
      - The slug page must:
        - Render as a full page
        - NOT auto-open the modal.
      - Modals should only open from in-app navigation.

      ------------------------------------------------
      3. Desktop Nav Default State
      ------------------------------------------------
      - On desktop:
        - Menu/nav is OPEN by default.
      - Closing remains optional (do not remove functionality).



      ------------------------------------------------
      Output:
      - List all modified files
      - Provide full updated components or diffs
